# This is a configuration file for the config package written
# by RStudio. To use, make sure the package `config` is installed,
# via console:
#
# R > install.packages("config")
#
# Then, you can load within a notebook chunk with `library(config)`.
#
# To use default config settings, simply write `config::get()`.
#
# You can learn more at:
#   https://cran.r-project.org/web/packages/config/vignettes/introduction.html.
default:
  path:
    edidata: 
      main: "/Volumes/shlab/Projects/EDI/data/"
      raw: "/Volumes/shlab/Projects/EDI/data/raw/"
      processed: "/Volumes/shlab/Projects/EDI/data/preprocessed/"
    cgedata: 
      main: "/Volumes/shlab/Projects/CGE/data/"
      raw: "/Volumes/shlab/Projects/CGE/data/raw/"
      processed: "/Volumes/shlab/Projects/CGE/data/preprocessed/"
    cgtdata: 
      main: "/Volumes/shlab/Projects/CGT/CGT_study2"
      raw: "/Volumes/shlab/Projects/CGT/CGT_study2/rawdata_study2"
      processed: "/Volumes/shlab/Projects/CGT/CGT_study2/processeddata_study2"